### PR TITLE
[ls] return unresolved packages as a warning instead of an error

### LINKED ISSUE #2510: 0.14.0-deva list outdated
### What happened?

Was testing out devbox ls —outdated and it error on 0.14.0-deva

### Steps to reproduce

1. `cd /tmp/devbox-0.14.0-deva`
2. `devbox add enchant.dev`
3. `devbox ls —outdated` errors with `Error: failed to fetch resolved package: enchant.out@latest: package not found`

### Command

_No response_

### devbox.json

```jsonc
{
  "$schema":  "https://raw.githubusercontent.com/jetify-com/devbox/0.14.0-deva/.schema/devbox.schema.json",
  "packages": ["enchant.out"],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

### Devbox version

0.14.0-deva

### Nix version

nix (Nix) 2.18.6

### What system does this bug occur on?

macOS (Apple Silicon)

### Debug logs

```
onfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2025-02-10T22:52:23.439-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2025-02-10T22:52:23.439-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/tmp/devbox/devbox.json dur=44.5µs
time=2025-02-10T22:52:23.439-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:204 msg="package doesn't need patching" pkg=enchant.out mode=auto
time=2025-02-10T22:52:23.459-06:00 level=DEBUG source=go.jetpack.io/devbox/nix/nix.go:143 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' --version --debug"
time=2025-02-10T22:52:23.504-06:00 level=DEBUG source=go.jetpack.io/devbox/nix/nix.go:143 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' --version --debug" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.pid=27364 cmd.code=0 cmd.dur=44.965333ms
time=2025-02-10T22:52:23.504-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2025-02-10T22:52:23.504-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2025-02-10T22:52:23.504-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/tmp/devbox/devbox.json dur=122.875µs
time=2025-02-10T22:52:23.504-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:204 msg="package doesn't need patching" pkg=enchant.out mode=auto
time=2025-02-10T22:52:23.504-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:204 msg="package doesn't need patching" pkg=enchant.out mode=auto
time=2025-02-10T22:52:23.504-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:204 msg="package doesn't need patching" pkg=enchant.out mode=auto
Error: failed to fetch resolved package: enchant.out@latest: package not found

time=2025-02-10T22:52:24.031-06:00 level=ERROR source=go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:70 msg="command error" execid=bf5d83deb45144fb8ba13edaaad2c3c4 stack="package not found\ngo.jetpack.io/devbox/internal/nix.init\n\t<autogenerated>:1\nruntime.doInit1\n\truntime/proc.go:7278\nruntime.doInit\n\truntime/proc.go:7245\nruntime.main\n\truntime/proc.go:254\nruntime.goexit\n\truntime/asm_arm64.s:1223"
time=2025-02-10T22:52:24.031-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2025-02-10T22:52:24.031-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2025-02-10T22:52:24.032-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/tmp/devbox/devbox.json dur=590.334µs
time=2025-02-10T22:52:24.032-06:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:204 msg="package doesn't need patching" pkg=enchant.out mode=auto
```

### PR DESCRIPTION
**Pull request by Lagoja**
## Summary

Fixes #2510 

Previously, `devbox ls --outdated` would error on packages that it could not resolve, like `stdenv.cc.cc.lib` or `darwin.apple_sdk.frameworks.IOKit`. This prevented devbox from checking if the rest of the packages were outdated. 

This PR changes the error to a warning, so the rest of the version checks can proceed

## How was it tested?

1. Create a devbox.json
2. Add standard packages using `devbox add`
3. Add `stdenv.cc.cc.lib` or `darwin.apple_sdk.frameworks.IOKit` to the project
4. Verify that `devbox ls --outdated` shows a warning for the non-versioned packages instead of an error.

### CODE REVIEW

File: internal/devbox/packages.go [hunk 1]
```diff
@@ -71,6 +73,12 @@ func (d *Devbox) Outdated(ctx context.Context) (map[string]UpdateVersion, error)
 		outdatedPackages[pkg.Versioned()] = UpdateVersion{Current: existingLockPackage.Version, Latest: lockPackage.Version}
 	}
 
+	if len(warnings) > 0 {
```
Comment (mikeland73) [inline internal/devbox/packages.go:76]: if statement is not needed (range empty or range nil both work as expected)

**Review by mikeland73 — APPROVED** [review]
